export const TRANSACTION_TYPE_DEPOSIT = 'DEPOSIT';
export const TRANSACTION_TYPE_TRANSFER = 'TRANSFER';
export const TRANSACTION_TYPE_CANCEL = 'CANCEL';

export const TRANSACTION_STATUS_PENDING = 'PENDING';
export const TRANSACTION_STATUS_COMPLETED = 'COMPLETED';
export const TRANSACTION_STATUS_CANCELLED = 'CANCELLED';
